In [1]:
import torch

In [2]:
import torch
torch.__version__, torch.cuda.is_available(), torch.cuda.get_device_name(0)


('2.7.1+cu118', True, 'NVIDIA GeForce MX250')

In [3]:
x=torch.tensor([[1,2],[3,4]])
print(x)

tensor([[1, 2],
        [3, 4]])


In [7]:
x=torch.ones(2,2,requires_grad=True)
y=x+2
z=y*y*3
out=z.mean()
out.backward()
print(x)
print(y)
print(z)
print(out)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
